name: "Odjezdy"
description: "Odjezdy dopravních prostředků ze zastávek"
version: "1.0.14"
image: "cibetik/odjezdy-{arch}"
slug: "departures"
init: false
arch:
  - aarch64
  - amd64
  - armv7

startup: application

ports:
  8001/tcp: 8001

ingress: true
ingress_port: 8001

options:
  APIKey: ""

schema:
  APIKey: str
