name: "Odjezdy"
description: "Odjezdy dopravních prostředků ze zastávek"
version: "1.0.8"
image: ghcr.io/cibetik/ha-addons:latest
slug: "departures"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

startup: application

ports:
  8001/tcp: 8001

ingress: true
ingress_port: 8001

options:
  APIKey: ""

schema:
  APIKey: str
